version: "3.7"
services:
  nats_1:
    image: "nats:2.0.0-linux"
    command: >
      -cluster nats://0.0.0.0:6222
      -routes nats://nats_1:6222,nats://nats_2:6222,nats://nats_3:6222
    networks:
      - net

  nats_2:
    image: "nats:2.0.0-linux"
    command: >
      -cluster nats://0.0.0.0:6222
      -routes nats://nats_1:6222,nats://nats_2:6222,nats://nats_3:6222
    networks:
      - net
    depends_on:
      - nats_1
      - nats_3

  nats_3:
    image: "nats:2.0.0-linux"
    command: >
      -cluster nats://0.0.0.0:6222
      -routes nats://nats_1:6222,nats://nats_2:6222,nats://nats_3:6222
    networks:
      - net
    depends_on:
      - nats_1

  nats_streaming_1:
    image: "nats-streaming:0.15.1-linux"
    command: >
      -store file -dir store -clustered -cluster_id nats_lab -cluster_node_id node_1
      -cluster_peers node_1,node_2,node_3
      -nats_server nats://nats_1:4222,nats://nats_2:4222,nats://nats_3:4222
    ports:
      - 14222:4222
      - 18222:8222
    networks:
      - net
    depends_on:
      - nats_1
      - nats_2
      - nats_3

  nats_streaming_2:
    image: "nats-streaming:0.15.1-linux"
    command: >
      -store file -dir store -clustered -cluster_id nats_lab -cluster_node_id node_2
      -cluster_peers node_1,node_2,node_3
      -nats_server nats://nats_1:4222,nats://nats_2:4222,nats://nats_3:4222
    ports:
      - 24222:4222
      - 28222:8222
    networks:
      - net
    depends_on:
      - nats_1
      - nats_2
      - nats_3

  nats_streaming_3:
    image: "nats-streaming:0.15.1-linux"
    command: >
      -store file -dir store -clustered -cluster_id nats_lab -cluster_node_id node_2
      -cluster_peers node_1,node_2,node_3
      -nats_server nats://nats_1:4222,nats://nats_2:4222,nats://nats_3:4222
    ports:
      - 34222:4222
      - 38222:8222
    networks:
      - net
    depends_on:
      - nats_1
      - nats_2
      - nats_3

  api:
    build:
      context: ./api
      args:
        NODE_ENV: ${ENV}
        PORT: ${PORT}
    command: ["npm", "start"]
    environment:
      - NODE_ENV=${ENV}
      - PORT=${PORT}
      - DEBUG_COLORS=${DEBUG_COLORS}
      - DEBUG=${DEBUG}
      - NATS_CONN=${NATS_CONN}
    volumes:
      - ./api/src:/home/node/app/src
      - ./api/package.json:/home/node/app/package.json
    ports:
      - ${PORT_PUBLISHED}:${PORT}
    networks:
      - net

  worker:
    build:
      context: ./worker
      args:
        NODE_ENV: ${ENV}
        PORT: ${PORT}
    command: ["npm", "start"]
    environment:
      - NODE_ENV=${ENV}
      - PORT=${PORT}
      - DEBUG_COLORS=${DEBUG_COLORS}
      - DEBUG=${DEBUG}
      - NATS_CONN=${NATS_CONN}
    volumes:
      - ./worker/bin:/home/node/app/bin
      - ./worker/src:/home/node/app/src
      - ./worker/package.json:/home/node/app/package.json
    ports:
      - ${PORT_PUBLISHED_WORKER}:${PORT}
    networks:
      - net

networks:
  net:
    name: ${AKA}_${ENV}_net
